"""
Azure Local HA/DR Architecture Diagram
Generated by Diagram agent
Date: 2026-01-30

Architecture Overview:
- 4 Azure Local clusters across 2 sites (Production + DR)
- 4 physical nodes per cluster (16 nodes total)
- Cluster A & C: VM workloads (Windows + Linux) with Hyper-V Replica
- Cluster B & D: AKS clusters in Active/Passive configuration
- SQL Server VMs: 3 in Production, 2 in DR (Always On AG)
- AKS: Windows containers (IIS), Linux containers, MinIO storage
- CI/CD pipeline per AKS cluster
- Azure Arc enabled VMs (Production site only)
- Azure Traffic Manager for AKS failover

Prerequisites:
- pip install diagrams
- Graphviz installed (apt-get install graphviz)

Generate PNG: python 03-des-diagram.py
"""

from diagrams import Diagram, Cluster, Edge
from diagrams.azure.compute import KubernetesServices, VMWindows, VMLinux
from diagrams.azure.database import SQLServers
from diagrams.azure.network import TrafficManagerProfiles, LoadBalancers, Firewall
from diagrams.azure.security import Defender, KeyVaults
from diagrams.azure.identity import ManagedIdentities, ActiveDirectory
from diagrams.azure.general import Helpsupport
from diagrams.azure.devops import Pipelines
from diagrams.azure.analytics import LogAnalyticsWorkspaces
from diagrams.onprem.network import Internet, Nginx
from diagrams.onprem.compute import Server
from diagrams.onprem.container import Docker
from diagrams.onprem.database import Mssql
from diagrams.generic.network import Router
from diagrams.generic.storage import Storage

# Diagram configuration - LR layout for side-by-side sites
graph_attr = {
    "fontsize": "16",
    "bgcolor": "#f5f5f5",
    "pad": "1.0",
    "splines": "spline",
    "nodesep": "0.4",
    "ranksep": "0.6",
}

cluster_attr = {
    "fontsize": "14",
    "bgcolor": "white",
}

with Diagram(
    "Azure Local HA/DR Architecture",
    show=False,
    direction="LR",
    filename="03-des-diagram",
    graph_attr=graph_attr
):
    # ==================== LEFT: PRODUCTION SITE ====================
    with Cluster("Production Site", graph_attr={"bgcolor": "#e8f5e9"}):
        
        with Cluster("Cluster A - VM Workloads"):
            with Cluster("Platform: Hyper-V + S2D"):
                prod_nodes_a = Server("4 Nodes")
            
            with Cluster("Arc-Enabled VMs"):
                prod_win = VMWindows("Windows\nVMs")
                prod_lin = VMLinux("Linux\nVMs")
            
            with Cluster("SQL Always On (Primary)"):
                prod_sql = Mssql("3x SQL\nServers")

        with Cluster("Cluster B - AKS Workloads"):
            with Cluster("Platform: Hyper-V + S2D"):
                prod_nodes_b = Server("4 Nodes")
            
            prod_lb = LoadBalancers("Load\nBalancer")
            prod_ingress = Nginx("Ingress")
            prod_aks = KubernetesServices("AKS\n(Active)")
            
            with Cluster("Containers"):
                prod_iis = Docker("IIS\n(Win)")
                prod_app = Docker("App\n(Linux)")
                prod_minio = Docker("MinIO\n(Linux)")

    # ==================== CENTER: AZURE CLOUD + WAN ====================
    with Cluster("Azure Cloud", graph_attr={"bgcolor": "#e3f2fd"}):
        users = Internet("Users")
        
        with Cluster("Global Services"):
            traffic_mgr = TrafficManagerProfiles("Traffic\nManager")
            entra = ActiveDirectory("Entra ID")
            defender = Defender("Defender")
        
        with Cluster("Azure Arc"):
            arc_servers = ManagedIdentities("Arc\nServers")
            arc_k8s = KubernetesServices("Arc K8s")
        
        with Cluster("Management"):
            update_mgr = Helpsupport("Update\nMgr")
            logs = LogAnalyticsWorkspaces("Log\nAnalytics")
            kv = KeyVaults("Key Vault")
        
        with Cluster("CI/CD"):
            cicd_prod = Pipelines("Pipeline\nCluster B")
            cicd_dr = Pipelines("Pipeline\nCluster D")

    wan = Router("Vodafone WAN")

    # ==================== RIGHT: DR SITE ====================
    with Cluster("DR Site", graph_attr={"bgcolor": "#fff3e0"}):
        
        with Cluster("Cluster C - VM Workloads"):
            with Cluster("Platform: Hyper-V + S2D"):
                dr_nodes_c = Server("4 Nodes")
            
            with Cluster("Hyper-V Replica VMs"):
                dr_win = VMWindows("Windows\nVMs")
                dr_lin = VMLinux("Linux\nVMs")
            
            with Cluster("SQL Always On (Secondary)"):
                dr_sql = Mssql("2x SQL\nServers")

        with Cluster("Cluster D - AKS Workloads"):
            with Cluster("Platform: Hyper-V + S2D"):
                dr_nodes_d = Server("4 Nodes")
            
            dr_lb = LoadBalancers("Load\nBalancer")
            dr_ingress = Nginx("Ingress")
            dr_aks = KubernetesServices("AKS\n(Passive)")
            
            with Cluster("Containers"):
                dr_iis = Docker("IIS\n(Win)")
                dr_app = Docker("App\n(Linux)")
                dr_minio = Docker("MinIO\n(Linux)")

    # ==================== CONNECTIONS ====================
    
    # User traffic
    users >> traffic_mgr
    traffic_mgr >> Edge(label="Active", color="green", style="bold") >> prod_lb
    traffic_mgr >> Edge(label="Standby", color="orange", style="dashed") >> dr_lb
    
    # Load Balancer flow
    prod_lb >> prod_ingress >> prod_aks >> prod_iis >> prod_app >> prod_minio
    dr_lb >> dr_ingress >> dr_aks >> dr_iis >> dr_app >> dr_minio

    # Azure Arc
    prod_win >> Edge(color="purple", style="dashed") >> arc_servers
    prod_lin >> Edge(color="purple", style="dashed") >> arc_servers
    prod_aks >> Edge(color="blue", style="dashed") >> arc_k8s
    dr_aks >> Edge(color="blue", style="dashed") >> arc_k8s

    # CI/CD
    cicd_prod >> Edge(color="darkblue") >> prod_aks
    cicd_dr >> Edge(color="darkblue") >> dr_aks

    # WAN replication
    prod_win >> Edge(label="Hyper-V\nReplica", color="darkgreen", style="bold") >> wan >> dr_win
    prod_lin >> Edge(color="darkgreen") >> wan >> dr_lin
    prod_sql >> Edge(label="SQL AG", color="blue", style="bold") >> wan >> dr_sql

    # SQL connections from AKS
    prod_app >> Edge(color="gray") >> prod_sql
    dr_app >> Edge(color="gray") >> dr_sql
    
    # Defender
    defender >> Edge(color="red", style="dotted") >> prod_aks
    defender >> Edge(color="red", style="dotted") >> dr_aks
