"""
Azure Architecture Diagram: SMB Landing Zone - Full Scenario
Generated by Diagram agent
Date: 2026-01-29

Scenario: Full (Azure Firewall + VPN Gateway)
Monthly Cost: ~$476
Features: Azure Firewall Basic, VPN Gateway VpnGw1AZ, VNet peering, UDR, Gateway Transit

Prerequisites:
- pip install diagrams
- Graphviz installed (choco install graphviz / brew install graphviz / apt-get install graphviz)

Generate PNG: python 03-des-diagram-full.py
"""

from diagrams import Diagram, Cluster, Edge
from diagrams.azure.network import (
    VirtualNetworks,
    Subnets,
    Firewall,
    VirtualNetworkGateways,
    DNSPrivateZones,
    NetworkSecurityGroupsClassic,
    RouteTables,
)
from diagrams.azure.compute import VM
from diagrams.azure.migration import MigrationProjects
from diagrams.azure.devops import ApplicationInsights
from diagrams.azure.general import CostManagement, Tags
from diagrams.azure.storage import RecoveryServicesVaults
from diagrams.onprem.compute import Server
from diagrams.generic.network import Firewall as GenericFirewall

# Diagram configuration
graph_attr = {
    "fontsize": "20",
    "bgcolor": "white",
    "pad": "0.5",
    "splines": "ortho",
    "nodesep": "0.8",
    "ranksep": "1.0",
}

edge_attr = {
    "fontsize": "10",
}

with Diagram(
    "SMB Landing Zone - Full Scenario (~$476/mo)",
    show=False,
    direction="TB",
    filename="03-des-diagram-full",
    graph_attr=graph_attr,
    edge_attr=edge_attr,
):

    # External entities
    onprem = Server("On-Premises\nVMware")

    with Cluster("Azure Subscription - swedencentral"):

        # Subscription-level services
        with Cluster("Subscription Services"):
            defender = ApplicationInsights("Defender for Cloud\n(Free Tier)")
            budget = CostManagement("Cost Management\nBudget $500/mo")
            policies = Tags("20 Azure Policies\n(Deny/Audit)")

        # Hub Resource Group
        with Cluster("rg-hub-slz-swc"):

            with Cluster("Hub VNet (10.0.0.0/23)"):

                with Cluster("AzureBastionSubnet (/26)"):
                    bastion = GenericFirewall("Azure Bastion\nDeveloper")

                with Cluster("AzureFirewallSubnet (/26)"):
                    firewall = Firewall("Azure Firewall\nBasic")

                with Cluster("GatewaySubnet (/27)"):
                    vpn = VirtualNetworkGateways("VPN Gateway\nVpnGw1AZ")

            # Hub supporting services
            dns = DNSPrivateZones("Private DNS Zone\nauto-registration")
            hub_nsg = NetworkSecurityGroupsClassic("Hub NSG\nDefault Deny")
            route_table = RouteTables("Route Table\n0.0.0.0/0 → FW")

        # Spoke Resource Group - PEERED with Gateway Transit + UDR
        with Cluster("rg-spoke-prod-swc"):

            with Cluster("Spoke VNet (10.0.2.0/23) ←→ Hub [Gateway Transit + UDR]"):

                with Cluster("WorkloadSubnet (/24) + UDR"):
                    spoke_nsg = NetworkSecurityGroupsClassic("Spoke NSG\nDefault Deny")
                    vms = [
                        VM("Migrated VM 1"),
                        VM("Migrated VM 2"),
                    ]

        # Migration Resource Group
        with Cluster("rg-migrate-slz-swc"):
            migrate = MigrationProjects("Azure Migrate\nVMware Assessment")

        # Monitor Resource Group
        with Cluster("rg-monitor-slz-swc"):
            logs = ApplicationInsights("Log Analytics\n500MB/day cap")

        # Backup Resource Group
        with Cluster("rg-backup-slz-swc"):
            vault = RecoveryServicesVaults("Recovery Services\nVault")

    # Data flow connections

    # On-premises to Azure (VPN)
    onprem >> Edge(label="S2S VPN\n(IPsec)", color="blue") >> vpn

    # VPN connects to Hub VNet
    vpn >> Edge(label="Gateway\nTransit", style="dashed") >> firewall

    # Bastion to VMs (management access)
    bastion >> Edge(label="RDP/SSH\n(secure)") >> vms[0]
    bastion >> Edge(label="", style="invis") >> vms[1]

    # VMs route through Firewall (via UDR)
    vms[0] >> Edge(label="UDR →") >> route_table
    vms[1] >> Edge(label="") >> route_table
    route_table >> Edge(label="Inspects") >> firewall
    firewall >> Edge(label="Outbound\nInternet", color="red") >> logs

    # VMs register in Private DNS
    vms[0] >> Edge(label="DNS\nAuto-reg", style="dotted") >> dns

    # Monitoring and backup connections
    vms[0] >> Edge(label="Logs", style="dotted") >> logs
    vms[0] >> Edge(label="Backup", style="dotted") >> vault

    # Azure Migrate assesses on-prem
    onprem >> Edge(label="Discovery\n& Assessment") >> migrate

    # NSG protects subnets
    spoke_nsg >> Edge(label="Protects", style="invis") >> vms[0]
