"""
Azure Architecture Diagram: SMB Ready Foundation - Overview (All Components)
Generated by Diagram agent
Date: 2026-01-27 (Updated: 2026-01-29)

This is the complete architecture overview showing ALL optional components.
For scenario-specific diagrams, see:
- 03-des-diagram-baseline.py   - NAT Gateway only (~$48/mo)
- 03-des-diagram-firewall.py   - Azure Firewall + UDR (~$336/mo)
- 03-des-diagram-vpn.py        - VPN Gateway + Gateway Transit (~$187/mo)
- 03-des-diagram-full.py       - Firewall + VPN + UDR (~$476/mo)

Prerequisites:
- pip install diagrams
- Graphviz installed (choco install graphviz / brew install graphviz / apt-get install graphviz)

Generate PNG: python 03-des-diagram.py
"""

from diagrams import Diagram, Cluster, Edge
from diagrams.azure.network import (
    VirtualNetworks,
    Subnets,
    Firewall,
    VirtualNetworkGateways,
    DNSPrivateZones,
    NetworkSecurityGroupsClassic,
    LocalNetworkGateways,
)
from diagrams.azure.compute import VM
from diagrams.azure.migration import MigrationProjects
from diagrams.azure.devops import ApplicationInsights
from diagrams.azure.general import CostManagement, Tags
from diagrams.azure.storage import RecoveryServicesVaults
from diagrams.onprem.compute import Server
from diagrams.generic.network import Firewall as GenericFirewall

# Diagram configuration
graph_attr = {
    "fontsize": "20",
    "bgcolor": "white",
    "pad": "0.5",
    "splines": "ortho",
    "nodesep": "0.8",
    "ranksep": "1.0",
}

edge_attr = {
    "fontsize": "10",
}

with Diagram(
    "SMB Ready Foundation - Azure Migrate Ready",
    show=False,
    direction="TB",
    filename="03-des-diagram",
    graph_attr=graph_attr,
    edge_attr=edge_attr,
):

    # External entities
    onprem = Server("On-Premises\nVMware")

    with Cluster("Azure Subscription - swedencentral"):

        # Subscription-level services
        with Cluster("Subscription Services"):
            defender = ApplicationInsights("Defender for Cloud\n(Free Tier)")
            budget = CostManagement("Cost Management\nBudget $500/mo")
            policies = Tags("20 Azure Policies\n(Deny/Audit)")

        # Hub Resource Group
        with Cluster("rg-hub-smb-swc"):

            with Cluster("Hub VNet (10.0.0.0/16)"):

                with Cluster("AzureBastionSubnet (/26)"):
                    bastion = GenericFirewall("Azure Bastion\nDeveloper")

                with Cluster("AzureFirewallSubnet (/26) [reserved]"):
                    firewall = Firewall("Azure Firewall\nBasic (Optional)")

                with Cluster("GatewaySubnet (/27) [reserved]"):
                    vpn = VirtualNetworkGateways("VPN Gateway\nVpnGw1AZ (Optional)")

            # Hub supporting services
            dns = DNSPrivateZones("Private DNS Zone\nauto-registration")
            hub_nsg = NetworkSecurityGroupsClassic("Hub NSG\nDefault Deny")

        # Spoke Resource Group
        with Cluster("rg-spoke-prod-swc"):

            with Cluster("Spoke VNet (10.1.0.0/16)"):

                with Cluster("WorkloadSubnet (/24)"):
                    spoke_nsg = NetworkSecurityGroupsClassic("Spoke NSG\nDefault Deny")
                    nat = LocalNetworkGateways("NAT Gateway\nStandard")
                    vms = [
                        VM("Migrated VM 1"),
                        VM("Migrated VM 2"),
                    ]

        # Migration Resource Group
        with Cluster("rg-migrate-smb-swc"):
            migrate = MigrationProjects("Azure Migrate\nVMware Assessment")

        # Monitor Resource Group
        with Cluster("rg-monitor-smb-swc"):
            logs = ApplicationInsights("Log Analytics\n500MB/day cap")

        # Backup Resource Group
        with Cluster("rg-backup-smb-swc"):
            vault = RecoveryServicesVaults("Recovery Services\nVault")

    # Data flow connections

    # On-premises to Azure (optional VPN)
    onprem >> Edge(label="S2S VPN\n(if enabled)", style="dashed") >> vpn

    # VPN connects to Hub VNet (when deployed)
    vpn >> Edge(label="VNet\nIntegration", style="dashed") >> firewall

    # Bastion to VMs (management access)
    bastion >> Edge(label="RDP/SSH\n(secure)") >> vms[0]
    bastion >> Edge(label="", style="invis") >> vms[1]

    # VMs use NAT Gateway for outbound
    vms[0] >> Edge(label="Outbound\nInternet") >> nat
    vms[1] >> Edge(label="") >> nat

    # Firewall inspects traffic (when deployed)
    firewall >> Edge(label="Inspects", style="dashed") >> nat

    # VMs register in Private DNS
    vms[0] >> Edge(label="DNS\nAuto-reg", style="dotted") >> dns

    # Monitoring and backup connections
    vms[0] >> Edge(label="Logs", style="dotted") >> logs
    vms[0] >> Edge(label="Backup", style="dotted") >> vault

    # Azure Migrate assesses on-prem
    onprem >> Edge(label="Discovery\n& Assessment") >> migrate

    # NSG protects subnets
    spoke_nsg >> Edge(label="Protects", style="invis") >> vms[0]
