"""
Azure Architecture Diagram: SMB Ready Foundation - VPN Scenario
Generated by Diagram agent
Date: 2026-01-29

Scenario: VPN (VPN Gateway + Gateway Transit)
Monthly Cost: ~$187
Features: VPN Gateway VpnGw1AZ, VNet peering with gateway transit, no Firewall

Prerequisites:
- pip install diagrams
- Graphviz installed (choco install graphviz / brew install graphviz / apt-get install graphviz)

Generate PNG: python 03-des-diagram-vpn.py
"""

from diagrams import Diagram, Cluster, Edge
from diagrams.azure.network import (
    VirtualNetworks,
    Subnets,
    VirtualNetworkGateways,
    DNSPrivateZones,
    NetworkSecurityGroupsClassic,
    LocalNetworkGateways,
)
from diagrams.azure.compute import VM
from diagrams.azure.migration import MigrationProjects
from diagrams.azure.devops import ApplicationInsights
from diagrams.azure.general import CostManagement, Tags
from diagrams.azure.storage import RecoveryServicesVaults
from diagrams.onprem.compute import Server
from diagrams.generic.network import Firewall as GenericFirewall

# Diagram configuration
graph_attr = {
    "fontsize": "20",
    "bgcolor": "white",
    "pad": "0.5",
    "splines": "ortho",
    "nodesep": "0.8",
    "ranksep": "1.0",
}

edge_attr = {
    "fontsize": "10",
}

with Diagram(
    "SMB Ready Foundation - VPN Scenario (~$187/mo)",
    show=False,
    direction="TB",
    filename="03-des-diagram-vpn",
    graph_attr=graph_attr,
    edge_attr=edge_attr,
):

    # External entities
    onprem = Server("On-Premises\nVMware")

    with Cluster("Azure Subscription - swedencentral"):

        # Subscription-level services
        with Cluster("Subscription Services"):
            defender = ApplicationInsights("Defender for Cloud\n(Free Tier)")
            budget = CostManagement("Cost Management\nBudget $500/mo")
            policies = Tags("20 Azure Policies\n(Deny/Audit)")

        # Hub Resource Group
        with Cluster("rg-hub-smb-swc"):

            with Cluster("Hub VNet (10.0.0.0/23)"):

                with Cluster("AzureBastionSubnet (/26)"):
                    bastion = GenericFirewall("Azure Bastion\nDeveloper")

                with Cluster("AzureFirewallSubnet (/26) [reserved]"):
                    fw_placeholder = Tags("Reserved\n(not deployed)")

                with Cluster("GatewaySubnet (/27)"):
                    vpn = VirtualNetworkGateways("VPN Gateway\nVpnGw1AZ")

            # Hub supporting services
            dns = DNSPrivateZones("Private DNS Zone\nauto-registration")
            hub_nsg = NetworkSecurityGroupsClassic("Hub NSG\nDefault Deny")

        # Spoke Resource Group - PEERED with Gateway Transit
        with Cluster("rg-spoke-prod-swc"):

            with Cluster("Spoke VNet (10.0.2.0/23) ←→ Hub [Gateway Transit]"):

                with Cluster("WorkloadSubnet (/24)"):
                    spoke_nsg = NetworkSecurityGroupsClassic("Spoke NSG\nDefault Deny")
                    nat = LocalNetworkGateways("NAT Gateway\nStandard")
                    vms = [
                        VM("Migrated VM 1"),
                        VM("Migrated VM 2"),
                    ]

        # Migration Resource Group
        with Cluster("rg-migrate-smb-swc"):
            migrate = MigrationProjects("Azure Migrate\nVMware Assessment")

        # Monitor Resource Group
        with Cluster("rg-monitor-smb-swc"):
            logs = ApplicationInsights("Log Analytics\n500MB/day cap")

        # Backup Resource Group
        with Cluster("rg-backup-smb-swc"):
            vault = RecoveryServicesVaults("Recovery Services\nVault")

    # Data flow connections

    # On-premises to Azure (VPN)
    onprem >> Edge(label="S2S VPN\n(IPsec)", color="blue") >> vpn

    # VPN connects to Spoke via Gateway Transit
    vpn >> Edge(label="Gateway\nTransit", style="dashed") >> vms[0]

    # Bastion to VMs (management access)
    bastion >> Edge(label="RDP/SSH\n(secure)") >> vms[0]
    bastion >> Edge(label="", style="invis") >> vms[1]

    # VMs use NAT Gateway for outbound
    vms[0] >> Edge(label="Outbound\nInternet") >> nat
    vms[1] >> Edge(label="") >> nat

    # VMs register in Private DNS
    vms[0] >> Edge(label="DNS\nAuto-reg", style="dotted") >> dns

    # Monitoring and backup connections
    vms[0] >> Edge(label="Logs", style="dotted") >> logs
    vms[0] >> Edge(label="Backup", style="dotted") >> vault

    # Azure Migrate assesses on-prem
    onprem >> Edge(label="Discovery\n& Assessment") >> migrate

    # NSG protects subnets
    spoke_nsg >> Edge(label="Protects", style="invis") >> vms[0]
